name: Build and Deploy via FTP to Azure Web App

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Restore dependencies
        run: dotnet restore eShopOnWeb.sln

      - name: Build
        run: dotnet build eShopOnWeb.sln --no-restore --configuration Release

      - name: Publish app
        run: dotnet publish src/Web/Web.csproj --configuration Release -o ./publish

      - name: Deploy via FTPS to Azure
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./publish/
          server-dir: /site/wwwroot/
