name: FTP Deploy

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.x'

    - name: Restore dependencies
      run: dotnet restore ./Tienda-electr贸nica-en-la-web.sln

    - name: Build
      run: dotnet build ./Tienda-electr贸nica-en-la-web.sln --configuration Release --no-restore

    - name: Publish
      run: dotnet publish ./Tienda-electr贸nica-en-la-web/Tienda-electr贸nica-en-la-web.csproj --configuration Release --output ./publish

    - name: FTP Deploy
      uses: SamKirkland/FTP-Deploy-Action@v4.3.4
      with:
        server: ${{ secrets.FTP_SERVER }}
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        protocol: ftps
        local-dir: ./publish/
        server-dir: /site/wwwroot/
